### ISSUE TITLE
Can't run initial-jobs-api branch

### ISSUE THREAD

**Issue by dstampher** [ghulamabbas2/jobs-api-unit-testing#1]
Executing npm run dev fails with an error.  I had to install nodemon globally, no problem.

After doing that, there is another error.  When cloning this branch of the repo, there is no config.env included.  The user has to create one manually, and search through the source code find the environment variable names that they need to set.  This is not a great experience for someone that is trying to learn.

Provide an example .env file in the repo, with default values meant to be set by the individual before running npm run dev.  Also mention that they cannot follow along unless they have an API key for AWS.

**Comment by DeepakDonde** [comment]
Need running copy of code.
Sharing the error dump from cmd:
```
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (D:\Interview\JestProject\jobs-api-unit-testing\node_modules\mongoose\lib\connection.js:695:11)
    at D:\Interview\JestProject\jobs-api-unit-testing\node_modules\mongoose\lib\index.js:414:10
    at D:\Interview\JestProject\jobs-api-unit-testing\node_modules\mongoose\lib\helpers\promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (D:\Interview\JestProject\jobs-api-unit-testing\node_modules\mongoose\lib\helpers\promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (D:\Interview\JestProject\jobs-api-unit-testing\node_modules\mongoose\lib\index.js:1288:10)
    at Mongoose.connect (D:\Interview\JestProject\jobs-api-unit-testing\node_modules\mongoose\lib\index.js:413:20)
    at connectDatabase (file:///D:/Interview/JestProject/jobs-api-unit-testing/config/database.js:4:12)
    at file:///D:/Interview/JestProject/jobs-api-unit-testing/server.js:10:1
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
[nodemon] app crashed - waiting for file changes before starting...
```
